name: Github simple-slack-notify demo
on: [push]
jobs:
    call-simple-slack-notify-from-pvmtriet232-repo:
        runs-on: ubuntu-latest
        steps: 
            - uses: pvmtriet232/simple-slack-notify@b204bd72c057a336fc9d18c37740602f77eace98
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              with:
                text: 'This is the simplest notification'
